# Generated by Django 5.0.1 on 2024-05-14 08:54

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=myauth.models.avatar_directory_path),
        ),
    ]
